LAYER_ONE_PROMPT = (
    "You are a smart and intelligent Named Entity and Relationship Recognition system. I will provide you the definition of the entities you need to extract, the sentence from where your extract the entities and the output format with examples.\n"
    "Entity Name and Definition:\n"
    "1. report: The most upstream reporting structure. The stream is report - section - field - part. Contain Properties: entitlements, maintainers, business_group, report_format, name\n"
    "2. section: The first level heading of a report. The stream is report - section - field - part. Contain Properties: name\n"
    "3. field: The second level heading of a report. The stream is report - section - field - part. Contain Properties: name, description\n"
    "4. part: The third level heading of a report. The stream is report - section - field - part. Contain Properties: name, description\n"
    "5. database: The most upstream part in the data source. The stream is database - table - column. Contain Properties: name\n"
    "6. table: The second part in the data source. The stream is database - table - column. Contain Properties: name\n"
    "7. column: The third part in the data source. The stream is database - table - column. Contain Properties: name\n"
    "8. model: The machine learning model used and related to some parts of the report or some parts of the database. Could have the connection between any elements (report, section, field, part) in a report, (database, table, column) in a database, or even anthor model regarding the model lineage. Contain Properties: output_column, performance_metrics, author, input_columns, name, created_at, parameters, version, metadata\n"
    "\n"
    "Output Format:\n"
    "[list of Named Entity and Relationship instances]\n"
    "Format of a Named Entity and Relationship instance:\n"
    "{'Entity': {Entity Properties}, 'Stuff Interested': [list of Stuff Information]}\n"
    "Format of Stuff Information:\n"
    "If this is a property but there is no information about the property, the Stuff Information is the name of the property\n"
    "If this is a property and there is information about it, the Stuff Information is {name of the property: property information}\n"
    "Note that the property must a valid property of the entity mentioned above e.g. we cannot have performance_metrics in the Stuff Interested when Entity is report.\n"
    "If this is an entity but there is no information about its properties, the Stuff Information is the name of the entity\n"
    "If this is an entity and there is information about its properties, the Stuff Information is the dictionary {name of the entity: {Entity Properties}}\n"
    "\n"
    "Note:\n"
    "\n"
    "1. If there is no information provides, fill UNKNOWN to the blank.\n"
    "2. If there is any invalid parenthesis in the output, convert it to the correct version.\n"
    "3. If there is empty dictionary, replace it with {'name': 'UNKNOWN'}\n"
    "4. The output logic should always follow the entity definition.\n"
    "\n"
    "Examples:\n"
    "\n"
    "1. Sentence: What are the performance metrics of model named model_23829389\n"
    "Output: [{'model': {'name': 'model_23829389'}, 'Stuff Interested': ['performance_metrics']}]\n"
    "\n"
    "2. Sentence: Who are the authors of model_1 and model_2?\n"
    "Output: [{'model': {'name': 'model_1'}, 'Stuff Interested': ['author']}, {'model':{'name': 'model_2'}, 'Stuff Interested': ['author']}]\n"
    "\n"
    "3. Sentence: What is the relationship between model model_1223 and database db_1234?\n"
    "Output: [{'model': {'name': 'model_1223'}, 'Stuff Interested': [{'database': {'name': 'db_1234'}}]}, {'database': {'name': 'db_1234'}, 'Stuff Interested': [{'model': {'name': 'model_1223'}}]}]\n"
    "\n"
    "4. Sentence: What are the fields of section Key Takeaways?\n"
    "Output: [{'section': {'name': 'Key Takeways'}, 'Stuff Interested': ['field']}]\n" 
    "\n"
    "5. Sentence: Which tables has the report named report_1 employed?\n"
    "Output: [{'report': {'name': 'report_1'}, 'Stuff Interested': ['table']}]\n"
    "\n"
    "6. Sentence: In report China Economy Growth, does the data used also involved in report_123 and model_42839829?\n"
    "Output: [{'report': {'name': 'China Economy Growth'}, 'Stuff Interested': ['database']}, {'report': {'name': 'report_123'}, 'Stuff Interested': ['database']}, {'model': {'name': 'model_42839829'}, 'Stuff Interested': ['database']}]\n"
    "\n"
    "7. Sentence: How many models are there that have accuracy bigger than 0.9?\n"
    "Output: [{'model': {'name': 'UNKNOWN'}, 'Stuff Interested': [{'accuracy': 'accuracy > 0.9'}]}]\n"
    "\n"
    "8. Sentence: Give the name of the reports that have the fields with description containing China?\n"
    "Output: [{'report': {'name': 'UNKNOWN'}, 'Stuff Interested': ['field']}, {'field': {'name': 'UNKNOWN'}, 'Stuff Interested': [{'description': 'contain word China'}]}}]"
    "\n"
    "10. Sentence: What reports are referenced by the report named report_1?\n"
    "Output: [{'report': {'name': 'report_1'}, 'Stuff Interested': ['report']}]\n"
    "\n"
    "11. Sentence: What is the relationship between model model_1 and model model_2?\n"
    "Output: \n"
    "\n"
    "12. Sentence: Which models utilize the table_1?\n"
    "Output: [{'table': {'name': 'table_1'}, 'Stuff Interested': ['model']}]\n"
    "\n"
    "13. Sentence: Which columns in table_1 are utilized in report_1?\n"
    "Output: [{'table': {'name': 'table_1'}, 'Stuff Interested': ['columns']}]\n"
    "\n"
)

LAYER_TWO_PROMPT = (
    "You are a smart and intelligent graph database query logic sorting system. I will give you one user requirement in the form of text and one python list representing the related query objects and relationship.\n"
    "I want to give you some background information about the graph database\n"
    "There are 8 Labels in the graph database: report, section, field, part, database, table, column, model.\n"
    "Relationship among these labels:\n"
    "report - section - field - part\n"
    "database - table - column\n"
    "a - b means that 1 node of label a can connect with multiple nodes of label b\n"
    "nodes of label model can connect with multiple nodes of any other label\n"
    "Regulation of creation of query logic sorting:\n"
    "A sorted query logic is a linked list representing by a python list: []\n"
    "A valid query logic always starts with a specified node (with some exceptions mentioned below)\n"
    "A specified node is the node with at least one property specified\n not 'UNKNOWN'\n"
    "Then follow the relationship to create the query order\n"
    "Given a set of input (user requirement(s), query objects and relationships), you should output [a set of query logic]\n"
    "\n"
    "Examples:\n"
    "\n"
    "1. input:\n"
    "User Requirement: What are the performance metrics of model named model_23829389?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_23829389'}, 'Stuff Interested': ['performance_metrics']}]\n"
    "Output: [[{'model': {'name': 'model_23829389'}}, 'performance_metrics']]\n"
    "\n"
    "2. input:\n"
    "User Requirement: Who are the authors of model_1 and model_2?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_1'}, 'Stuff Interested': ['author']}, {'model':{'name': 'model_2'}, 'Stuff Interested': ['author']}]\n"
    "Output: [[{'model': {'name': 'model_1'}, 'author'}], [{'model':{'name': 'model_2'}, 'author']]\n"
    "\n"
    "3. input:\n"
    "User Requirement: What is the relationship between model model_1223 and database db_1234?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_1223'}, 'Stuff Interested': [{'database': {'name': 'db_1234'}}]}, {'database': {'name': 'db_1234'}, 'Stuff Interested': [{'model': {'name': 'model_1223'}}]}]\n"
    "Output: [[{'model': {'name': 'model_1223'}}, {'database': {'name': 'db_1234'}}], [{'database': {'name': 'db_1234'}}, {'model': {'name': 'model_1223'}}]]\n"    
    "\n"    
)

LAYER_THREE_PROMPT = (
    "You are a sophisticated and intelligent Cypher query generation system. I will provide you with a Python list representing the sorted query logic, derived from user requirements concerning a graph database structured around various entities such as reports, sections, fields, parts, databases, tables, columns, and models, along with their relationships. Your task is to translate this logic into Cypher queries that can be executed in a Neo4j database to fulfill the given requirements.\n"
    "\n"
    "Background Information:\n"
    "The graph database contains 8 labels: report, section, field, part, database, table, column, model. The relationships among these labels are structured as follows:\n"
    "- report -> section -> field -> part\n"
    "- database -> table -> column\n"
    "- model nodes can connect with multiple nodes of any other label.\n"
    "\n"
    "Cypher Query Generation Guidelines:\n"
    "- Start with a MATCH clause targeting the specified node(s) based on the query logic provided. A specified node is defined as a node with at least one known property value.\n"
    "- Follow the relationship path defined in the query logic to construct the rest of the query, using appropriate relationship patterns in Cypher syntax.\n"
    "- Use WHERE clauses to filter nodes based on the properties provided in the query logic.\n"
    "- Return the final result set as specified in the query logic, focusing on the 'Stuff Interested' properties or entities.\n"
    "\n"
    "Given the sorted query logic as input, generate the corresponding Cypher query or queries that can be used to query or manipulate data in the Neo4j graph database.\n"
    "\n"
    "This is the database schema you can reference when generating the query.\n"
    "Node properties are the following: report {report_format: STRING, business_group: STRING, name: STRING, entitlements: STRING, maintainers: STRING},section {name: STRING},field {name: STRING, description: STRING},model {created_at: STRING, author: STRING, parameters: STRING, output_column: STRING, input_columns: STRING, version: INTEGER, performence_metric: STRING, name: STRING, mean_absolute_error: INTEGER, root_mean_squared_error: INTEGER, r_squared: FLOAT, author_email: STRING, accuracy: FLOAT, precision: FLOAT, recall: FLOAT},mapping {report_name: STRING, upstream_source_type: STRING},database {name: STRING},table {name: STRING},column {name: STRING}\n"
    "Relationship properties are the following:(:report)-[:HAS_SECTION]->(:section),(:report)-[:REFERS_TO]->(:field),(:section)-[:HAS_FIELD]->(:field),(:model)-[:HAS_INPUT]->(:column),(:model)-[:IS_INPUT_OF]->(:model),(:model)-[:Iterate]->(:model),(:mapping)-[:MAP]->(:field),(:mapping)-[:MAP]->(:model),(:mapping)-[:MAP]->(:database),(:database)-[:HAS_TABLE]->(:table),(:table)-[:HAS_COLUMN]->(:column)\n"
    "Examples:\n"
    "\n"
    "1. input:\n"
    "User Requirement: What are the performance metrics of model named model_23829389?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_23829389'}, 'Stuff Interested': ['performance_metrics']}]\n"
    "Query Logic Extraction: [[{'model': {'name': 'model_23829389'}}, 'performance_metrics']]\n"
    "Output: MATCH (m:model {name: 'model_23829389'}) RETURN m.performance_metrics AS PerformanceMetrics\n"
    "\n"
    "2. input:\n"
    "User Requirement: Who are the authors of model_1 and model_2?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_1'}, 'Stuff Interested': ['author']}, {'model':{'name': 'model_2'}, 'Stuff Interested': ['author']}]\n"
    "Query Logic Extraction: [[{'model': {'name': 'model_1'}, 'author'}], [{'model':{'name': 'model_2'}, 'author']]\n"
    "Output: MATCH (m:model) WHERE m.name IN ['model_1', 'model_2'] RETURN m.name AS ModelName, m.author AS Author\n"
    "\n"
    "3. input:\n"
    "User Requirement: What is the relationship between model model_1223 and database db_1234?\n"
    "Query Objects and Relationships: [{'model': {'name': 'model_1223'}, 'Stuff Interested': [{'database': {'name': 'db_1234'}}]}, {'database': {'name': 'db_1234'}, 'Stuff Interested': [{'model': {'name': 'model_1223'}}]}]\n"
    "MATCH (m:model)-[:HAS_INPUT]->(c:column)<-[:HAS_COLUMN]-(t:table)<-[:HAS_TABLE]-(d:database) WHERE m.name = 'model_1223' AND d.name = 'db_1234' RETURN m, d, t, c\n"
    "\n"
    "4. input:\n"
    "User Requirement: What are the fields of section Key Takeaways?\n"
    "Query Objects and Relationships: [{'section': {'name': 'Key Takeways'}, 'Stuff Interested': ['field']}]\n" 
    "MATCH (s:section {name: 'Key Takeaways'})-[:HAS_FIELD]->(f:field) RETURN f.name AS FieldName\n" 
    "5. input:\n"
    "User Requirement: Which tables has the report named report_1 employed?\n"
    "Query Objects and Relationships: [{'report': {'name': 'report_1'}, 'Stuff Interested': ['table']}]\n" 
    "MATCH (r:report{name: 'Saudi Arabia Budget Report 2024'})-[:HAS_SECTION]->(s:section)-[:HAS_FIELD]->(f:field)<-[:MAP]-(ma:mapping)-[:MAP]->(m:model)-[:HAS_INPUT]->(c:column)<-[:HAS_COLUMN]-(t:table) RETURN DISTINCT t\n" 
    "7. input:\n"
    "User Requirement: How many models in the field Real GDP Recovery have an accuracy bigger than 0.9?\n"
    "Query Objects and Relationships: [{'model': {'name': 'UNKNOWN'}, 'Stuff Interested': [{'accuracy': 'accuracy > 0.9'}]}]\n"
    "MATCH (f:field {name: 'Real GDP Recovery'})<-[:MAP]-(m:mapping)-[:MAP]->(mod:model) WHERE mod.accuracy > 0.9 RETURN COUNT(mod) AS ModelCount\n"
    "9. input:\n"
    "User Requirement: Which models are predicting revenue?\n"
    "MATCH (model) WHERE model.output_column = 'revenue' RETURN model\n"
    "10. input:\n"
    "User Requirement: Could you please give me the name of the reports that have the fields with description containing 'China'?\n"
    "MATCH (r:report)-[:HAS_SECTION]->(s:section)-[:HAS_FIELD]->(f:field) WHERE f.description CONTAINS 'China' RETURN DISTINCT r.name AS ReportName\n"
    "15. input:\n"
    "User Requirement: What is the relationship between model model_701015291 and model model_701015292?\n"
    "MATCH (model1 {name: 'model_701015292'}) -[r]- (model2 {name: 'model_701015291'}) RETURN TYPE(r) AS RelationshipType\n"
    "16. input:\n"
    "User Requirement: Does the model_925814632 and model_701015291 use the table economic_indicators_tb?\n"
    "MATCH (t:table {name: 'economic_indicators_tb'}) OPTIONAL MATCH (m1:model {name: 'model_925814632'})-[:HAS_INPUT]->(:column)<-[:HAS_COLUMN]-(t) OPTIONAL MATCH (m2:model {name: 'model_701015291'})-[:HAS_INPUT]->(:column)<-[:HAS_COLUMN]-(t) WITH COLLECT(m1) AS models1, COLLECT(m2) AS models2 RETURN CASE WHEN ANY(m IN models1 WHERE m IS NOT NULL) AND ANY(m IN models2 WHERE m IS NOT NULL) THEN 'yes' ELSE 'no' END AS result\n"
    "Note: When generating cypher codes, you don't need to use [:PART_OF]. The examples provided are illustrative. Your task involves adapting this methodology to handle various structured inputs to generate accurate and functional Cypher queries.\n"
)

QA_PROMPT = """
Answer the question based on the context below like a human being. I will provide you with the graph database schema and user question and its graph database data result. 
Please return a natural language rephrase of the answer to the given question. 
The answer should have key related to the question. Do not include "LLM" in your response.
"""

node_properties_query = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE NOT type = "RELATIONSHIP" AND elementType = "node"
WITH label AS nodeLabels, collect(property) AS properties
RETURN {labels: nodeLabels, properties: properties} AS output
"""

rel_properties_query = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE NOT type = "RELATIONSHIP" AND elementType = "relationship"
WITH label AS nodeLabels, collect(property) AS properties
RETURN {type: nodeLabels, properties: properties} AS output
"""

rel_query = """
CALL apoc.meta.data()
YIELD label, other, elementType, type, property
WHERE type = "RELATIONSHIP" AND elementType = "node"
RETURN {source: label, relationship: property, target: other} AS output
"""

def schema_text(node_props, rel_props, rels):
    return f"""
  This is the schema representation of the Neo4j database.
  Node properties are the following: 
  {node_props} 
  Relationship properties are the following: 
  {rel_props} 
  Relationship point from source to target nodes 
  {rels} 
  Make sure to respect relationship types and directions 
  """